[package]
name = "fishgame"
version = "0.1.0"
authors = ["Fedor Logachev <not.fl3@gmail.com>"]
edition = "2018"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
nanoserde = "0.1.29"
macroquad = { version = "0.3" }
macroquad-platformer = "0.1"
macroquad-tiled = "0.1"
macroquad-profiler = "0.1"
macroquad-particles = {version = "0.1", features = ["nanoserde"] }

#gamepad-rs = { path = "https://github.com/unrust/gamepad-rs.git" }
gamepad-rs = { path = "./gamepad-rs" }

[patch.crates-io]
macroquad = { git = "https://github.com/not-fl3/macroquad.git", rev = "1fdc24c" }
macroquad-particles = { git = "https://github.com/not-fl3/macroquad.git", rev = "1fdc24c" }
macroquad-tiled = { git = "https://github.com/not-fl3/macroquad.git", rev = "1fdc24c" }
macroquad-platformer = { git = "https://github.com/not-fl3/macroquad.git", rev = "1fdc24c" }

# macroquad = { path = "../macroquad" }
# macroquad-particles = { path = "../macroquad/particles" }
# macroquad-tiled = { path = "../macroquad/tiled" }
# macroquad-platformer = { path = "../macroquad/physics-platformer" }
# macroquad-profiler = { path = "../macroquad/profiler" }

