[package]
authors = ["Fish Fight Contributors"]
description = "A tactical 2D shooter"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "fishfight"
version = "0.4.2"

[target.'cfg(target_arch = "wasm32")'.lib]
crate-type = ["cdylib"]

[features]
default = []

[workspace]
members = ["core"]

[profile.dev.package."*"]
opt-level = 3

[dependencies]
core = {path = "./core", package = "fishfight-core"}
# ultimate = { path = "../FishFight-ultimate", package = "fishfight-ultimate", optional = true }
ff-particles = {version = "0.1", features = ["serde"]}
fishsticks = {git = "https://github.com/fishfight/fishsticks", default-features = false, features = ["gilrs"]}
hecs = {path = "../hv-dev/hv-ecs"}
hv-lua = {path = "../hv-dev/hv-lua"}#imported so its macro's work
macroquad = {version = "0.3.10"}
macroquad-platformer = "0.1"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tealr = {path = "../tealr/tealr", features = ["mlua", "hv_lua", "mlua_vendored", "mlua_luajit", "mlua_serialize", "mlua_send", "derive"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.74"
