[package]
authors = ["Fish Fight Contributors"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "fishfight-core"
version = "0.4.2"

[dependencies]
async-trait = "0.1.52"
fishsticks = {git = "https://github.com/fishfight/fishsticks", default-features = false, features = ["gilrs"]}
hecs = {git = "https://github.com/sdleffler/hv-dev"}
hv-alchemy = {git = "https://github.com/sdleffler/hv-dev"}
hv-cell = {git = "https://github.com/sdleffler/hv-dev"}
hv-lua = {git = "https://github.com/sdleffler/hv-dev"}#imported so its macro's work
macroquad = {version = "0.3.10"}
serde = {version = "1.0", package = "serde", features = ["derive"]}
serde_json = {version = "1.0"}
tealr = {git = "https://github.com/lenscas/tealr", branch = "temporary/feature/add_support_for_hv_lua", features = ["mlua", "hv_lua", "mlua_macros", "mlua_vendored", "mlua_luajit", "mlua_serialize", "derive"]}
toml = "0.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = {version = "0.2", features = ["js"]}
wasm-bindgen = "0.2.74"
